/**
 * Centralized UI copy — swap this object for Hindi (or any language) later.
 * No user-facing text should be hard-coded in components.
 */
export const strings = {
  common: {
    appName: 'Actionable Justice OS',
    teamLine: 'Team Maverick · Kamakshi & Chirag',
    loading: 'Loading…',
    error: 'Something went wrong',
    retry: 'Try again',
    empty: 'Nothing here yet',
    back: 'Go back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    signIn: 'Sign in',
    signUp: 'Sign up',
    signOut: 'Sign out',
  },
  hero: {
    badge: 'System Online',
    title: 'Actionable Justice OS',
    subtitle:
      'Execution-First legal redressal — from emergency SOS to autonomous follow-ups.',
    cta: 'Try the demo',
    ctaSecondary: 'Learn more',
    layerLabels: [
      { id: 0, name: 'Urgency', feature: 'Pulse SOS' },
      { id: 1, name: 'Intelligence', feature: 'Statute Guard' },
      { id: 2, name: 'Execution', feature: 'Direct-File' },
      { id: 3, name: 'Persistence', feature: 'Persistence Bot' },
    ],
  },
  chat: {
    title: 'Describe your grievance',
    placeholder: 'e.g. "Loud DJ next door at 1 am every weekend…"',
    voiceBtn: 'Voice input',
    voicePlaceholder: 'Voice input coming soon',
    pinLabel: 'PIN code (6 digits)',
    pinPlaceholder: '110001',
    submitBtn: 'Analyse',
    previewTitle: 'Analysis Result',
    urgencyLabel: 'Urgency',
    categoryLabel: 'Category',
    statuteLabel: 'Applicable Law',
    sectionLabel: 'Section',
    citationsLabel: 'Citations',
    officerLabel: 'Nodal Officer',
    needsLawyer: 'AI confidence is low — consider consulting a lawyer.',
    confirmBtn: 'File this grievance',
    confirmingBtn: 'Filing…',
    sosWarning: 'This situation may require immediate help.',
    sosAction: 'Go to SOS',
    sosMessage: 'Emergency detected — tap to trigger SOS.',
  },
  grievance: {
    timelineTitle: 'Chain of Action',
    statusLabels: {
      PENDING: 'Pending',
      FILED: 'Filed',
      FOLLOWED_UP: 'Followed up',
      ESCALATED: 'Escalated',
      RESOLVED: 'Resolved',
    } as Record<string, string>,
    eventLabels: {
      FILED: 'Grievance filed',
      FOLLOWUP_7D: '7-day follow-up',
      ESCALATION_14D: '14-day escalation',
      SOS_BROADCAST: 'SOS broadcast',
    } as Record<string, string>,
    channelLabels: {
      EMAIL: 'Email',
      SMS: 'SMS',
      WHATSAPP: 'WhatsApp',
      SYSTEM: 'System',
    } as Record<string, string>,
    noEvents: 'No events yet — the notice is being processed.',
    officerCard: 'Assigned Officer',
    statuteCard: 'Legal Basis',
    refreshHint: 'Auto-refreshing every 10 seconds',
  },
  dashboard: {
    title: 'Your Grievances',
    emptyState: 'You haven\'t filed any grievances yet.',
    emptyCta: 'File a new grievance',
    statusGroups: {
      active: 'Active',
      resolved: 'Resolved',
    },
    eventCount: 'events',
    viewDetails: 'View details',
  },
  sos: {
    title: 'Emergency SOS',
    holdToTrigger: 'Press & hold for 1 second to trigger SOS',
    releasing: 'Release to cancel',
    triggering: 'Sending SOS…',
    triggered: 'SOS Sent',
    call112: 'Call 112 (ERSS)',
    call112Sub: 'Emergency Response Support System',
    nearbyPolice: 'Nearest Police Stations',
    nearbyHospitals: 'Nearest Hospitals',
    deliveryStatus: 'Delivery Status',
    smsLabel: 'SMS',
    whatsappLabel: 'WhatsApp',
    sent: 'Sent',
    failed: 'Failed',
    noContacts:
      'Add emergency contacts first to use SOS.',
    addContacts: 'Add contacts',
    locationError: 'Could not get your location. Please enable GPS.',
    openMap: 'Open in Maps',
  },
  onboard: {
    title: 'Emergency Contacts',
    subtitle: 'These contacts will receive SOS alerts with your GPS location.',
    addContact: 'Add contact',
    nameLabel: 'Full name',
    namePlaceholder: 'e.g. Priya Sharma',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+91 98765 43210',
    relationLabel: 'Relation (optional)',
    relationPlaceholder: 'e.g. Mother, Friend',
    saveBtn: 'Save contact',
    savingBtn: 'Saving…',
    deleteConfirm: 'Remove this contact?',
    minContactWarning: 'Add at least one contact so SOS can reach someone.',
    noContacts: 'No emergency contacts added yet.',
  },
} as const;
